### ISSUE TITLE
Flag: Choose whether to clean up resources on failing tests

### ISSUE THREAD

**Issue by sadath-12** [knative-extensions/reconciler-test#669]
Follow up from the issue https://github.com/knative/eventing/issues/7649

cc @Cali0707 

**Problem**

Currently our system does not clean up resources if the e2e fails . This could be helpful for debugging but what if your working on some difficult tests and you run multiple tests everytime all the resources will be lying here and there and its irritating again to bring up new cluster and again to setup knative and repeat this process over and over again

Add a flag which takes the value from an environment variable to choose whether to delete resources on failed tests

**Exit Criteria**
you should not be seeing any new namespaces or resources lying on your cluster after running e2e tests by turning this flag on

**Comment by pierDipi** [comment]
It was decided that not deleting resources is a good default behavior also because I usually just delete the namespace of the test after root causing the failure as deleting the resources automatically will not give me the chance to root cause and debug the issue properly, what is the workflow you're thinking if the flag would be on and resources are gone no matter what's the test result ?

**Comment by Cali0707** [comment]
@pierDipi I generally agree with you, I think this is coming from this slack discussion: https://cloud-native.slack.com/archives/C04LMU33V1S/p1706811265752229
